7.POST/api/articles/article_id/comments - Ready for Review
bobbynagra92/be-news-api pull request #5
Opened 2023-03-29 10:54 UTC by bobbynagra92

2023-03-29 11:09 UTC, callumu21 requested changes
Really nice code so far! Just missing a few extra tests that I've put in a comment below. Once you've added those in, please resubmit this PR for review 👍

2023-03-29 11:09 UTC, callumu21 commented on __tests__/app.test.js
> +  test('ERROR 400: Responds with an error message when attempting to POST an invalid comment', () => {
Make sure to keep this test description tied to the specific condition you're changing (e.g. when attempting to post with an invalid body property)

2023-03-29 11:09 UTC, callumu21 commented on __tests__/app.test.js
> +       });
Just missing a few more tests here:

1. What happens when a comment body has a username that isn't in our system?
2. What happens when a comment body contains valid properties (username and body), as well as an extra property? (This should still be a successful request)
3. What happens if we try to post a comment to a valid review_id that doesn't exist in the system

2023-03-29 11:09 UTC, callumu21 commented on models/articles.model.js
> +exports.addComment = (article_id, comment) => {
Nice and readable model

2023-03-30 09:39 UTC, B7Bprog requested changes
Hey Bobby, please see my comments and refactor your tests, then send us a quick PR with it.

2023-03-30 09:39 UTC, B7Bprog commented on __tests__/app.test.js
> +  test('ERROR 400: Responds with an error message when attempting to POST an invalid username not yet in our database', () => {
This one supposed to be a 404 'Not found' error. Please refactor it.

2023-03-30 09:39 UTC, B7Bprog commented on __tests__/app.test.js
> +      .expect(400)
Expect 404 here.

2023-03-30 09:39 UTC, B7Bprog commented on __tests__/app.test.js
> +  test('ERROR 400: Responds with an error message when passed an article_id which does not yet exist', () => {
This should be a 404 'Not found'.

2023-03-30 09:39 UTC, B7Bprog commented on __tests__/app.test.js
> +      .expect(400)
Expect 404 here.

2023-03-30 10:46 UTC, callumu21 approved these changes
Nice work, Bobby! Looks good to merge 👍

2023-03-30 11:02 UTC, merged